---
title: "Mutate"
output: html_document
editor_options: 
  chunk_output_type: console
chunk: wrangle
jupyter:
  jupytext:
    cell_metadata_filter: name,tags,-all
    formats: Rmd//Rmd,notebooks//ipynb
    notebook_metadata_filter: purview
    text_representation:
      extension: .Rmd
      format_name: rmarkdown
      format_version: '1.2'
      jupytext_version: 1.13.8
  kernelspec:
    display_name: venv-intro-to-siuba
    language: python
    name: venv-intro-to-siuba
  purview:
    branch: master
    repo: machow/intro-to-siuba
    url: https://mybinder.org
    useBinder: 1
    useStorage: 1
---

```{python setup, tags=c("input-details", "setup")}
# TODO: explain how to run this, and that they only need the gist (loads tools)

# wranglign ---------
import pandas as pd
from siuba import *

# plotting ----------
from plotnine import *

theme_set(theme_classic(base_family = "Noto Sans CJK JP"))

# data --------------
from music_top200 import music_top200, track_features

# student support ----------
from siuba import pipe
from IPython.display import HTML, display
from siututor import Blank
___ = Blank()

# DataFrame display --------
pd.set_option("display.max_rows", 6)

from IPython import get_ipython
# special ipython function to get the html formatter
html_formatter = get_ipython().display_formatter.formatters['text/html']

# here, we avoid the default df._repr_html_ method, since it inlines css
# (style tags make vue angry)
html_formatter.for_type(
    pd.DataFrame,
    lambda df: df.to_html(max_rows = pd.get_option("display.max_rows"), show_dimensions = True)
)

# remove the <ggplot: (528...)> printout
html_formatter.for_type(ggplot, lambda g: "")

```

```{python active="", eval=FALSE}
import slides from '../slides/01d-slides.markdown'

<RevealSlides :slides="slides" />

```


### Exercise 0:

Delete the `#` symbol on the line `# music_top200`. This symbol is called a comment, and causes everything to the right of it to be ignored.

```{python}
# I am a helpful not. I am not code!

# music_top200
```

### Exercise 1:

Currently, the `duration` is calculated in seconds.

* Delete (uncomment) the `#` symbol in the code.
* Complete the code to convert duration to milliseconds.

<details>
  <summary>hint</summary>
  
  > Delete the # symbol. This is called a comment. When it is the first non-blank on a line, it stops that line from being run.
  
  > 1 second is 1000 milliseconds. So you would multiply the duration by 1000.
</details>

```{python}
(music_top200
  # >> mutate(___ = ___)
)
```


### Exercise 2:

Uncomment the mutate in the pipe below. Can you fix the two errors in it?

It should return data with a new column on the right, that divides position by 200.


```{python}
(music_top200
  # >> mutate(new position = position / 200)
)
```

```{python tags=c("solution-code")}
(music_top200
  >> mutate(new_position = _.position / 200)
)
```

### Exercise 3: 

The mutate below uses code from a future chapter to calculate how many letters are in each artist's name.

Which artist with the shortest name has the most streams?

<details>
  <summary>hint</summary>
  
  > You'll need to use an arrange in the pipe with 2 arguments.
</details>

```{python}
(music_top200
  >> mutate(artist_length = _.artist.str.len())
)
```

```{python tags=c("solution-code")}
(music_top200
  >> mutate(artist_length = _.artist.str.len())
  >> arrange(_.artist_length, -_.streams)
)
```

```{python active="", eval=FALSE}

<prompt-expandable header="">

<q-multiple-choice>
  <q-opt text="V, for their track in Indonesia"><span>That's right!</span></q-opt>
  <q-opt text="V, for their track in Hong Kong"><span>That's the right artist, but did you sort by most streams first?</span></q-opt>
  <q-opt text="F, for their track in Finland"><span>Incorrect. Did you sort by most streams first?</span></q-opt>
    <q-opt text="F, for their track in Hong Kong"><span>Incorrect. Did you sort by most streams first?</span></q-opt>
</q-multiple-choice>

</prompt-expandable>

```
