---
title: "Wrap up"
output: html_document
editor_options: 
  chunk_output_type: console
chunk: wrangle
jupyter:
  jupytext:
    cell_metadata_filter: name,tags,-all
    formats: Rmd//Rmd,notebooks//ipynb
    text_representation:
      extension: .Rmd
      format_name: rmarkdown
      format_version: '1.2'
      jupytext_version: 1.5.0
  kernelspec:
    display_name: Python 3
    language: python
    name: python3
---

```{python setup, tags=c("input-details", "setup")}
# TODO: explain how to run this, and that they only need the gist (loads tools)
import pandas as pd
from siuba import arrange, select, mutate, filter, _
from plotnine import ggplot, geom_point, coord_flip, aes, labs

# temporary until I figure out where to put data
fname = "https://siublocks.s3.us-east-2.amazonaws.com/course-data/music200.csv"
music_top200 = pd.read_csv(fname)

# tracks
fname = "https://siublocks.s3.us-east-2.amazonaws.com/course-data/track_features.csv"
track_features = pd.read_csv(fname)


# TODO: shift into a package or file
from siututor import Blank
___ = Blank()
# from siuba import pipe
# from IPython.display import HTML, display
# ___ = pipe(lambda x: display(HTML("⚠️: <b>Don't forget to replace all the blanks!<b>")) and _)

pd.set_option("display.max_rows", 6)

from IPython import get_ipython
# special ipython function to get the html formatter
html_formatter = get_ipython().display_formatter.formatters['text/html']

# when you see a Shout object, call the shout_html function on it
html_formatter.for_type(pd.DataFrame, lambda df: df.to_html(max_rows = pd.get_option("display.max_rows")))
```

### Putting it together (WORK IN PROGRESS)

TODO: this will be slides explaining importing and comments. Student should be able to produce a valid python file that someone (with python experience) could run.

Importing is how you get the data (like `music_top200`) and verbs into Python.

```python
from siuba import *
from plotnine import *

from music_top200 import *
```

Comments mean that you can start a line with `#` to ignore all the code in it

```python
# this is just a helpful message
# the code below here won't run
# music_top200
```


### Exercise 1:

The code below imports everything from siuba.

* Add lines to import everything from `plotnine` and `music_top200` as well.

```{python}
from siuba import *


```

### Exercise 2:

For the artist with the top track in Spain, what country has the most streams for one of their tracks?

Note: you may need to code multiple times.

<details>
  <summary>hint</summary>
    
  > First, find the artist in the top position in Spain. After, can you get only that artists tracks? Once you do that you should be close!
    
</details>

```{python}
(
    
)
```


```{python tags=c("solution-code")}
# Note: I would run the pipe with...
#   * only the commented out filter first, to get the artist (KAROL G)
#   * then, with the uncommented filter and arrange
(music_top200 
  # >> filter(_.country == "Spain")
  >> filter(_.artist == "KAROL G")
  >> arrange(-_.streams)
)
```

### Exercise 3:

```{python}
(music_top200
  >> mutate(___)
  >> mutate(stream_seconds = ___)
  # >> ggplot(aes("stream_seconds", "position", color = "duration"))
  # + geom_point()
)
```


```{python tags=c("solution-code")}
(music_top200
  >> filter(_.country == "Hong Kong")
  >> mutate(stream_seconds = _.streams * _.duration)
  >> ggplot(aes("stream_seconds", "position", color = "duration"))
  + geom_point()
)
```
