---
title: "Getting started"
output: html_document
editor_options: 
  chunk_output_type: console
chunk: visualize
jupyter:
  jupytext:
    cell_metadata_filter: name,tags,-all
    formats: Rmd//Rmd,notebooks//ipynb
    notebook_metadata_filter: purview
    text_representation:
      extension: .Rmd
      format_name: rmarkdown
      format_version: '1.2'
      jupytext_version: 1.5.0
  kernelspec:
    display_name: Python 3
    language: python
    name: python3
  purview:
    branch: master
    repo: machow/purview
    url: https://mybinder.org
    useBinder: 1
    useStorage: 1
---

```{python setup, tags=c("input-details", "setup")}
# TODO: explain how to run this, and that they only need the gist (loads tools)

# wranglign ---------
import pandas as pd
from siuba import *

# plotting ----------
from plotnine import *

theme_set(theme_classic(base_family = "Noto Sans CJK JP"))

# data --------------
fname = "/Users/machow/Dropbox/Repo/siublocks-org/intro-tidyverse/tutorial/data/music200.csv"
#fname = "https://siublocks.s3.us-east-2.amazonaws.com/course-data/music200.csv"
music_top200 = pd.read_csv(fname)

# tracks
fname = "/Users/machow/Dropbox/Repo/siublocks-org/intro-tidyverse/tutorial/data/track_features.csv"
#fname = "https://siublocks.s3.us-east-2.amazonaws.com/course-data/track_features.csv"
track_features = pd.read_csv(fname)

# student support ----------
from siuba import pipe
from IPython.display import HTML, display
from siututor import Blank
___ = Blank()

# DataFrame display --------
pd.set_option("display.max_rows", 6)

from IPython import get_ipython
# special ipython function to get the html formatter
html_formatter = get_ipython().display_formatter.formatters['text/html']

# when you see a Shout object, call the shout_html function on it
html_formatter.for_type(pd.DataFrame, lambda df: df.to_html(max_rows = pd.get_option("display.max_rows")))

```

```{python active="", eval=FALSE}
import slides from '../slides/02-slides.markdown'

<RevealSlides :slides="slides" />

```

<!-- #region tags=["exercise"] -->
### Exercise 1: 

In this exercise, there are two code cells. The first defines variables for tracks by different artists. The second creates a plot.

Interact with the plot code to answer the following:

* Who has the widest range of danceability? (i.e. biggist difference between highest and lowest)
<!-- #endregion -->

```{python}
roddy = (
  track_features
  >> filter(_.artist == "Roddy Ricch")
)

billie = (
  track_features
  >> filter(_.artist == "Billie Eilish")
)

other = (
  track_features
  >> filter(_.artist == "ITZY")
)

other
```

```{python}
(roddy
  >> ggplot(aes("danceability", "speechiness"))
   + geom_point()
   + expand_limits(x = [0, 1], y = [0, 1])
)
```

```{python tags=c("solution-code")}
import pandas as pd
all_together = pd.concat([roddy, billie, other])

(all_together
  >> ggplot(aes("danceability", "speechiness", color = "artist"))
   + geom_point()
   + expand_limits(x = [0, 1], y = [0, 1])
)
```

<!-- #region tags=["exercise"] -->
### Exercise 2:

Does it look like there any extremely popular songs over 15 minutes long?

There is not one concrete answer to this question.
Make a plot below, and come up with an answer you might share with another person.
<!-- #endregion -->

```{python}
(track_features
  >> ggplot()

)
```

```{python tags=c("solution-code")}
(track_features
  >> ggplot(aes("duration", "popularity"))
   + geom_point()
)
```

<!-- #region -->
<details>
<summary>possible answers</summary>
    
<a target="_blank" href="https://v.usetapes.com/XhWxJ9lAox">screencast</a>
    
    
</details>
<!-- #endregion -->

<!-- #region tags=["exercise"] -->
### Exercise 3:

Does the lowest energy track belong to a "low energy" artist?

Filter the track_features data to create two variables

* **artist_low**: tracks for the artist with the lowest energy track.
* **artist_high**: tracks for the artist with the highest energy track.

After examining plots of both artists, does the one with the lowest energy track seem to have lower energy songs in general?
<!-- #endregion -->

```{python}
# this code is to help you examine track energy levels 

(
  track_features
  >> arrange(_.energy)
)
```

```{python}
# create artist_low variable here

artist_low = (
    
)
```

```{python}
# create artist_high variable here

 
```

```{python}
# examine plots of each artist, to answer question

(___

)
```
