---
title: "Summarize"
output: html_document
editor_options: 
  chunk_output_type: console
chunk: summarize
jupyter:
  jupytext:
    cell_metadata_filter: name,tags,-all
    formats: Rmd//Rmd,notebooks//ipynb
    notebook_metadata_filter: purview
    text_representation:
      extension: .Rmd
      format_name: rmarkdown
      format_version: '1.2'
      jupytext_version: 1.5.0
  kernelspec:
    display_name: Python 3
    language: python
    name: python3
  purview:
    branch: master
    repo: machow/purview
    url: https://mybinder.org
    useBinder: 1
    useStorage: 1
---

```{python setup, tags=c("input-details", "setup")}
# TODO: explain how to run this, and that they only need the gist (loads tools)

# wranglign ---------
import pandas as pd
from siuba import *

# plotting ----------
from plotnine import *

theme_set(theme_classic(base_family = "Noto Sans CJK JP"))

# data --------------
fname = "/Users/machow/Dropbox/Repo/siublocks-org/intro-tidyverse/tutorial/data/music200.csv"
#fname = "https://siublocks.s3.us-east-2.amazonaws.com/course-data/music200.csv"
music_top200 = pd.read_csv(fname)

# tracks
fname = "/Users/machow/Dropbox/Repo/siublocks-org/intro-tidyverse/tutorial/data/track_features.csv"
#fname = "https://siublocks.s3.us-east-2.amazonaws.com/course-data/track_features.csv"
track_features = pd.read_csv(fname)

# student support ----------
from siuba import pipe
from IPython.display import HTML, display
from siututor import Blank
___ = Blank()

# DataFrame display --------
pd.set_option("display.max_rows", 6)

from IPython import get_ipython
# special ipython function to get the html formatter
html_formatter = get_ipython().display_formatter.formatters['text/html']

# when you see a Shout object, call the shout_html function on it
html_formatter.for_type(pd.DataFrame, lambda df: df.to_html(max_rows = pd.get_option("display.max_rows")))

```

```{python active="", eval=FALSE}

import slides from '../slides/03a-slides.markdown'

<RevealSlides :slides="slides" />

```

### Exercise 1:

The code below calculates the average duration.

* Uncomment the summarize verb.
* Change it to calculate median duration.
* Make sure to change the resulting column name to indicate its a median.

```{python}
(music_top200
  #>> summarize(avg_duration = _.duration.mean())
)
```

```{python tags=c("solution-code")}
(music_top200
  >> summarize(median_duration = _.duration.median(), ttl_streams = _.streams.sum())
)
```

Q: what is the median duration?

<details><summary>answer</summary>201.084</details>


Q: Add a second argument to summarize, which calculates the sum of streams. How large is it?

<details><summary>answer</summary>301,822,525</details>


### Exercise 2:

Use verbs you learned in chapter 1 to do the following:

* find the track with the lowest duration
* subset the data to keep only the row for that track

(Note, you may need to run code multiple times)

```{python}
(music_top200

)
```

Now, use summarize to calculate the min duration, and the max duration directly.

```{python}
(music_top200

)
```

Why would you use summarize like this, rather than the arrange and filter approach?

* Too many observations in data.
* The min and max values might be in different observations (rows).
* The arrange and filter approach can do anything summarize can.
* 


### Exercise 3:

The examples below show what happens verbs like filter and mutate use methods like `.mean()`.

```{python}
# create column for average streams
(music_top200
  >> mutate(avg_streams = _.streams.mean())
)
```

```{python}
# keep observations where streams are above average
(music_top200
  >> filter(_.streams < _.streams.mean())
)
```

Based on the examples above, can you use only the filter verb to get the most streamed song in all the data?

```{python}
# modify the filter verb below

(music_top200
  >> filter()
)
```
